name: Deploy dist folder
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        run: |
          echo "Checking out code..."
          echo "Current branch: ${{ github.ref }}"